apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: message-fun
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
     matchLabels:
      app: message-fun
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app: message-fun
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: api
        image: quay.io/unahur.arqsw/messagefun.api
        resources: 
          requests:
            memory: "90Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: MessageBusFun__RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user
              key: default-password
              optional: false
        - name: MessageBusFun__RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user
              key: default-user
              optional: false
        - name: MessageBusFun__RabbitMQ__Host	
          value: rabbitmq://rabbitmq:5672/
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: message-fun
    app.kubernetes.io/component: api
spec:
  selector:
    app: message-fun
    app.kubernetes.io/component: api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  labels:
    app: message-fun
    app.kubernetes.io/component: api
    release: monitoring
spec:
  selector:
    matchLabels:
      app: message-fun
      app.kubernetes.io/component: api
  endpoints:
  - port: http
    scheme: http
    interval: 15s
    scrapeTimeout: 14s
    path: /metrics