apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-user
  labels:
    app: message-fun
data:
  default-user: ZGVzYQ==
  default-password: ZGVzYXJyb2xsbw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: message-fun
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
     matchLabels:
      app: message-fun
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        app: message-fun
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: masstransit/rabbitmq:latest
        resources: {}
        ports:
        - name: amqp
          containerPort: 5672
        - name: management
          containerPort: 15672
        - name: metrics
          containerPort: 15692
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user
              key: default-user
              optional: false
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-user
              key: default-password
              optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: message-fun
    app.kubernetes.io/component: rabbitmq
spec:
  selector:
    app: message-fun
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: metrics
      protocol: TCP
      port: 15692
    - name: management
      protocol: TCP
      port: 15672
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  tls:
    - hosts:
        - rabbit.jpettinari.localdev.me
      secretName: rabbitmq-tls
  rules:
    - host: rabbit.jpettinari.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  name: management
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  labels:
    # labels defined in spec.serviceMonitorSelector.matchLabels
    release: monitoring
spec:
  endpoints:
    - port: metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
    - port: metrics
      scheme: http
      path: /metrics/detailed
      params:
        family:
          - queue_coarse_metrics
          - queue_metrics
      interval: 15s
      scrapeTimeout: 14s
  selector:
    matchLabels:
      app: message-fun
      app.kubernetes.io/component: rabbitmq
